---
- hosts: kubernetes_worker_nodes
  vars_files:
  - env_variables
  tasks:
  - name: Copying token to worker nodes
    copy: src={{ token_file }} dest=join_token.sh

  - name: Joining worker nodes with kubernetes master
    shell: |
     kubeadm reset -f
     sh join_token.sh
