apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  mysql-root-password: cGFzc3dvcmQ=
  mysql-database: ZGF0YWJhc2U=
  mysql-user: dXNlcm5hbWU=
  mysql-password: cGFzc3dvcmQ=
